apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyginusobi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyginusobi
  template:
    metadata:
      labels:
        app: hyginusobi
    spec:
      containers:
      - name: hyginusobi
        image: 982081093653.dkr.ecr.us-west-2.amazonaws.com/obi
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hyginusobi
    k8s-app: hyginusobi
  name: hyginusobi
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: hyginusobi
